name: Require dev as source
# This workflow is run on every pull requests on main.
# It aims to blocks any of said PRs wich doesn't comes from the dev branch
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]

jobs:
  check-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        if: ${{ github.head_ref != 'dev' }}
        run: |
          echo "::error title=Illegal-pull-request-source::All pull requests to the main branch must come from the dev branch."
          exit 1